### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by erhuabushuo** [kivy/audiostream#11]
Cython version 0.21.1

sudo python setup.py install
running install
running build
running build_py
running build_ext
cythoning audiostream/sources/thread.pyx to audiostream/sources/thread.c
## Error compiling Cython file:

...
import cython, array
##       ^

audiostream/sources/thread.pyx:1:7: Compiler crash in AnalyseDeclarationsTransform

File 'ModuleNode.py', line 103, in analyse_declarations: ModuleNode(thread.pyx:1:0,
    full_module_name = 'audiostream.sources.thread')
File 'Nodes.py', line 387, in analyse_declarations: StatListNode(thread.pyx:1:0)
File 'Nodes.py', line 387, in analyse_declarations: StatListNode(thread.pyx:1:15)
File 'Nodes.py', line 6920, in analyse_declarations: CImportStatNode(thread.pyx:1:7,
    as_name = u'cython',
    module_name = u'cython')

Compiler crash traceback from this point on:
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Nodes.py", line 6920, in analyse_declarations
    module_scope = env.find_module(self.module_name, self.pos)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Symtab.py", line 1101, in find_module
    module_name, relative_to=None if relative_level == 0 else self.parent_module, pos=pos)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 140, in find_module
    pxd_pathname = self.find_pxd_file(qualified_name, pos)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 192, in find_pxd_file
    pxd = self.search_include_directories(qualified_name, ".pxd", pos, sys_path=True)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 233, in search_include_directories
    tuple(self.include_directories), qualified_name, suffix, pos, include, sys_path)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Utils.py", line 22, in wrapper
    res = cache[args] = f(*args)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Utils.py", line 111, in search_include_directories
    path = os.path.join(dir, dotted_filename)
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 12: ordinal not in range(128)
building 'audiostream.sources.thread' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/SDL -I. -I/usr/include/SDL -I/usr/include/python2.7 -c audiostream/sources/thread.c -o build/temp.linux-x86_64-2.7/audiostream/sources/thread.o -ggdb -O2
audiostream/sources/thread.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
##

**Comment by jbsidis** [comment]
You can try to install python 3.8 or higher, sudo apt-get install python3 and then you can try the compilation python3.8 -m setup.py

**Comment by dark-dayone** [comment]
I have python3.9 installed but i still have the same error. It just won't install.

**Comment by Julian-O** [comment]
👋 We use the issue tracker exclusively for bug reports and feature requests.
However, this issue appears to be a support request. Please use our   [support channels](https://github.com/kivy/kivy/blob/master/README.md#support)            to get help with the project.
            
Let us know if this comment was made in error, and we'll be happy to reopen the issue.
