### ISSUE TITLE
Can't record 

### ISSUE THREAD

**Issue by 2n2u** [kivy/audiostream#16]
Running this bit of code:

def mic_callback(buf):
    print 'got', len(buf)
    frames.append(buf)
    print ('size of frames: ' + len(frames))

def bcallback(instance):

```
    mic = get_input(callback=mic_callback, source='mic')
    mic.start()

    #mic.poll()
    time.sleep(5)

    mic.stop()
```

class MyApp(App):
    def build(self):

```
    btn1 = Button(text='Audio Record')
    btn1.bind(on_press=bcallback)

    return btn1
```

if **name** == '**main**':
    MyApp().run()

and using logcat I can see that mic_callback isn't working since there isn't any print on logcat.

I've tried to change source to 'default' also, but doesn't work either.
##

**Comment by 2n2u** [comment]
I've tried this with KitKat and Lollipop, none of them work.

**Comment by cidermole** [comment]
The problem with the example is that you explicitly need a `buffersize`.

I would propose to
1) change the documentation to fix the example, and/or
2) set default `buffersize` similar to https://github.com/cidermole/audiostream/commit/dacf648bdc6bc9d16d65dd2a1aa02882940d8112

**Comment by 2n2u** [comment]
Yap I've solved the issue that way a long time ago. Closed.
