### ISSUE TITLE
JNI RegisterNatives called with pending exception java.lang.ClassNotFoundException: Didn't find class "org.audiostream.AudioIn"

### ISSUE THREAD

**Issue by iacoposk8** [kivy/audiostream#37]
Hi, I've created a [Google colab](https://colab.research.google.com/drive/1i3bgDgrb2li7jLIOU3in7YDZ5Owh_WBj?usp=sharing) so you can simply recreate the error.

My code is:
```
from audiostream import get_input
from android.permissions import request_permissions, Permission
request_permissions([Permission.RECORD_AUDIO])
def mic_callback(buf):
    print("got", len(buf))
print("KEYWORD_TO_SEARCH_IN_ADB_LOGCAT")
mic = get_input(callback=mic_callback)
```
but in adb logcat I read: 

> 02-25 10:53:48.359  1299  1568 F org.test.myapp: java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: JNI RegisterNatives called with pending exception java.lang.ClassNotFoundException: Didn't find class "org.audiostream.AudioIn" on path: DexPathList[[zip file "/data/app/org.test.myapp-VZcDiTQAVptYQlU1RG8YjQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.test.myapp-VZcDiTQAVptYQlU1RG8YjQ==/lib/arm, /data/app/org.test.myapp-VZcDiTQAVptYQlU1RG8YjQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]

and then, the application crashed.

Thanks for your help. I believe that if we create a working google colab it can also be integrated into the homepage to be used as a starting point.

**Comment by adarsh1783** [comment]
getting the same error 😔
can someone please help us ?

**Comment by senti-mkyu** [comment]
hi, did you use buildozer for android application?

I solved this issue by copying java source directory of the audiostream package to dists/myapp/src/main/java/org
(it can be found in audiostream/audiostream/platform/android/org)

I don't know why buildozer didn't copy it to the dists directory.

**Comment by adarsh1783** [comment]
thanks bro, it worked. 
Now If I am thinking about it looks that I should have thought of this.

**Comment by Julian-O** [comment]
👋 We use the issue tracker exclusively for bug reports and feature requests.
However, this issue appears to be a support request. Please use our   [support channels](https://github.com/kivy/kivy/blob/master/README.md#support)            to get help with the project.
            
Let us know if this comment was made in error, and we'll be happy to reopen the issue.
