### ISSUE TITLE
AudioOutput channels remains at value 2

### ISSUE THREAD

**Issue by PascaL-IT** [kivy/audiostream#38]
Cannot set AudioOutput channels at value 1

Test program: 
----------------
from kivy.core.audio import SoundLoader
from audiostream import get_output
sound = SoundLoader.load('sounds/kit1/clap.wav')
if sound:
    print("Sound found at %s" % sound.source)
    print("Sound is %.3f seconds" % sound.length)
    sound.play()
stream = get_output(channels=1, rate=44100, buffersize=1024)
print(type(stream))

Output:
--------
Sound found at C:\...\sounds\kit1\clap.wav
Sound is 0.522 seconds
AudioOutput ask for 44100 1
AudioOutput got 44100 2

![ScreenHunter_clipboard](https://user-images.githubusercontent.com/36189996/110829640-a59b7280-8298-11eb-99b2-43937332c46d.jpg)

if 
  stream = get_output(channels=1, rate=22050, buffersize=512)
then
  AudioOutput ask for 22050 1
  AudioOutput got 22050 2

Environment:
--------------
Python 3.7.3 
[INFO   ] [Logger      ] Record log in C:\Users\User\.kivy\logs\kivy_21-03-11_72.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.18
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\User\.pyenv\pyenv-win\versions\3.7.3\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\User\.pyenv\pyenv-win\versions\3.7.3\python.exe"
[INFO   ] [AudioGstplayer] Using Gstreamer 1.16.0.0
[INFO   ] [Audio       ] Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer ignored)

Windows 8.1
![image](https://user-images.githubusercontent.com/36189996/112942852-06e49200-9131-11eb-9066-5eca47479d15.png)

**Comment by vladimir-gui** [comment]
Hi, same problem here on windows 10, kivy2.0.0, it's doing a speedy sound for me.


Thanks to helping us

**Comment by steforte** [comment]
Same problem,
For a long time  I had exactly the same error (2 channels) and then suddenly I even get 8 channels.
So the number of channels allowed can change, over time (not during execution, on different run() ), surprising, isn't it ?

**Comment by Julian-O** [comment]
👋 We use the issue tracker exclusively for bug reports and feature requests.
However, this issue appears to be a support request. Please use our   [support channels](https://github.com/kivy/kivy/blob/master/README.md#support)            to get help with the project.
            
Let us know if this comment was made in error, and we'll be happy to reopen the issue.
