### ISSUE TITLE
ModuleNotFoundError: No module named 'audiostream.core' Tried on python3 and python2

### ISSUE THREAD

**Issue by YsGrandi** [kivy/audiostream#39]
I'm having problems installing audiostream on Ubuntu 20.10
first tried installing for python3 and got this error when importing audiostream : 
`import audiostream`
outputs : 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/gorou92/audiostream/audiostream/audiostream/__init__.py", line 19, in <module>
>     from audiostream.core import *
> ModuleNotFoundError: No module named 'audiostream.core'

and in python2 

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "audiostream/__init__.py", line 19, in <module>
    from audiostream.core import *
ImportError: No module named core

**Comment by thyme4soup** [comment]
How did you install it?
I ran into this issue too. I had to add
```
import pyximport
pyximport.install()
```
to `__init__.py` and delete the `core.pyx` after installing

Judging by the path you posted, I think you're installing locally like I was. I think doing the same thing will work for you

**Comment by Julian-O** [comment]
👋 We use the issue tracker exclusively for bug reports and feature requests.
However, this issue appears to be a support request. Please use our   [support channels](https://github.com/kivy/kivy/blob/master/README.md#support)            to get help with the project.
            
Let us know if this comment was made in error, and we'll be happy to reopen the issue.
