### ISSUE TITLE
Can't Install AudioStream In Windows Please help

### ISSUE THREAD

**Issue by Asalerm** [kivy/audiostream#43]
I have tried my best to install AudioStream in my Windows 10 Laptop but it failed still.

**Comment by Julian-O** [comment]
👋 We use the issue tracker exclusively for bug reports and feature requests.
However, this issue appears to be a support request. Please use our   [support channels](https://github.com/kivy/kivy/blob/master/README.md#support)            to get help with the project.
            
Let us know if this comment was made in error, and we'll be happy to reopen the issue.
