### ISSUE TITLE
sound is crackled

### ISSUE THREAD

**Issue by inheekwak** [kivy/audiostream#46]
I'm making a sound classification android app by using kivy and audiostream module.

But when I recorded the sound from outside through mic, the sound is crackled (The sound is kind of cut off).
I change the devices and tried other things but still sound is unclear.
Do you how to make the sound smoothly? (I checked the document but there was no function for that.) 
or is there anyway to solve it?

Thank you:)

**Comment by Julian-O** [comment]
👋 We use the issue tracker exclusively for bug reports and feature requests.
However, this issue appears to be a support request. Please use our   [support channels](https://github.com/kivy/kivy/blob/master/README.md#support)            to get help with the project.
            
Let us know if this comment was made in error, and we'll be happy to reopen the issue.
