### ISSUE TITLE
Get_bytes call too many times

### ISSUE THREAD

**Issue by pascalloria** [kivy/audiostream#47]
Hello ,
Before anything thanks for the works done on this AudioStream module.

I have an issue that i can't find a solution.  I have a python Kivy app who use  the Threadsource method. so i cut my sound in step  

1 step = 1/4 BPM = (samplerate *15/BPM)  samples   so it should call the function Get_bytes 4*BPM but it's call way more so my sound is read very fast can you help me ?

Thanks in advance

**Comment by Julian-O** [comment]
👋 We use the issue tracker exclusively for bug reports and feature requests.
However, this issue appears to be a support request. Please use our   [support channels](https://github.com/kivy/kivy/blob/master/README.md#support)            to get help with the project.
            
Let us know if this comment was made in error, and we'll be happy to reopen the issue.
