### ISSUE TITLE
installation on windows

### ISSUE THREAD

**Issue by USER4247** [kivy/audiostream#49]
running install
running build
running build_py
running build_ext
skipping 'audiostream\sources\thread.c' Cython extension (up-to-date)
skipping 'audiostream\sources\wave.c' Cython extension (up-to-date)
skipping 'audiostream\sources\puredata.c' Cython extension (up-to-date)
skipping 'audiostream\core.c' Cython extension (up-to-date)
building 'audiostream.sources.thread' extension
error: Unable to find vcvarsall.bat

I used python setup.py install by changing directory via cmd

**Comment by Julian-O** [comment]
👋 We use the issue tracker exclusively for bug reports and feature requests.
However, this issue appears to be a support request. Please use our   [support channels](https://github.com/kivy/kivy/blob/master/README.md#support)            to get help with the project.
            
Let us know if this comment was made in error, and we'll be happy to reopen the issue.
