### ISSUE TITLE
 ImportError: cannot import name 'get_input' from 'audiostream' (unknown location)

### ISSUE THREAD

**Issue by sameermahajan** [kivy/audiostream#50]
I installed audiostream on my mac with python 3.9. When I try your example of recording from microphone at line

`from audiostream import get_input
`
I get the error of:

` ImportError: cannot import name 'get_input' from 'audiostream' (unknown location)
`

Any ideas?

**Comment by Julian-O** [comment]
👋 We use the issue tracker exclusively for bug reports and feature requests.
However, this issue appears to be a support request. Please use our   [support channels](https://github.com/kivy/kivy/blob/master/README.md#support)            to get help with the project.
            
Let us know if this comment was made in error, and we'll be happy to reopen the issue.
