### ISSUE TITLE
Linker error on MacOS Ventura 13.4.1

### ISSUE THREAD

**Issue by Goldybin** [kivy/audiostream#51]
Hello, 
I tried to install your library on MacOS Ventura with Python 3.9 (Anaconda). Unfortunately it resulted in a linker error, please see below. Any advices are much appreciated, thank you!

warning: audiostream/ringbuffer.pxi:144:14: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
warning: audiostream/ringbuffer.pxi:144:27: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
audiostream/platform/mac_ext.m:77:2: warning: 'PyEval_InitThreads' is deprecated [-Wdeprecated-declarations]
        PyEval_InitThreads();
        ^
/Users/a/opt/anaconda3/include/python3.9/ceval.h:130:1: note: 'PyEval_InitThreads' has been explicitly marked deprecated here
Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
^
/Users/a/opt/anaconda3/include/python3.9/pyport.h:508:54: note: expanded from macro 'Py_DEPRECATED'
#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                     ^
audiostream/platform/mac_ext.m:132:14: warning: 'AudioHardwareGetProperty' is deprecated: first deprecated in macOS 10.6 [-Wdeprecated-declarations]
    status = AudioHardwareGetProperty(
             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreAudio.framework/Headers/AudioHardwareDeprecated.h:342:1: note: 'AudioHardwareGetProperty' has been explicitly marked deprecated here
AudioHardwareGetProperty(   AudioHardwarePropertyID inPropertyID,
^
audiostream/platform/mac_ext.m:168:34: warning: 'AudioUnitSampleType' is deprecated: The concept of canonical formats is deprecated [-Wdeprecated-declarations]
        size_t bytesPerSample = sizeof (AudioUnitSampleType);
                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreAudioTypes.framework/Headers/CoreAudioBaseTypes.h:191:1: note: 'AudioUnitSampleType' has been explicitly marked deprecated here
CA_CANONICAL_DEPRECATED typedef Float32     AudioUnitSampleType;
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreAudioTypes.framework/Headers/CoreAudioBaseTypes.h:29:52: note: expanded from macro 'CA_CANONICAL_DEPRECATED'
    #define CA_CANONICAL_DEPRECATED __attribute__((deprecated("The concept of canonical formats is deprecated")))
                                                   ^
audiostream/platform/mac_ext.m:168:9: warning: unused variable 'bytesPerSample' [-Wunused-variable]
        size_t bytesPerSample = sizeof (AudioUnitSampleType);
               ^
**4 warnings generated.
ld: library not found for -lSDL
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/clang' failed with exit code 1**

**Comment by Julian-O** [comment]
👋 We use the issue tracker exclusively for bug reports and feature requests.
However, this issue appears to be a support request. Please use our   [support channels](https://github.com/kivy/kivy/blob/master/README.md#support)            to get help with the project.
            
Let us know if this comment was made in error, and we'll be happy to reopen the issue.
