### ISSUE TITLE
Problem installing in Ubuntu 12.04 /usr/bin/ld: cannot find -lSDL /usr/bin/ld: cannot find -lSDL_mixer

### ISSUE THREAD

**Issue by jmokoistinen** [kivy/audiostream#6]
I have problems installing the project. Am I missing some package or symbolic link? 

This is what I got:
sudo python setup.py install
running install
running build
running build_py
running build_ext
skipping 'audiostream/sources/thread.c' Cython extension (up-to-date)
building 'audiostream.sources.thread' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/SDL -I. -I/usr/include/SDL -I/usr/include/python2.7 -c audiostream/sources/thread.c -o build/temp.linux-x86_64-2.7/audiostream/sources/thread.o -ggdb -O2
gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/audiostream/sources/thread.o -lSDL -lSDL_mixer -o build/lib.linux-x86_64-2.7/audiostream/sources/thread.so
/usr/bin/ld: cannot find -lSDL
/usr/bin/ld: cannot find -lSDL_mixer
collect2: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

**Comment by pankajkgupta** [comment]
I had the same problem and this solved my problem- 
https://www.programmersought.com/article/72976612256/
